export const FEATURE_FLAGS = {
  HOME: true,
  PROFILE: false,
  SEARCH: true,
  CR_CORNER: false,
  GROUPS: true,
  CLASSROOM: true,
  INSTITUTIONS: true,
  DEPARTMENTS: true,
  FRIENDS: true,
  GAMING: false,
  NOTIFICATIONS: false,
  MESSAGES: true,
  STUDY_HELPER: false,
  OPEN_DISCUSSION: false,
  CAREER_HUB: false,
  STORE: false,
  TUITION: false,
  VIDEOS: false,
  MORE: false,
  SETTINGS: true,
  FILES: false,
  SAVED: true,
  BLOOD_DONATION: false,
  BOX: true,
  QUICK_SHARE: true,
};
