const AUTH_KEYS = {
  CURRENT_USER: "CURRENT_USER",
  FEATURE_FLAGS: "FEATURE_FLAGS",
} as const;

const GAMING_KEYS = {
  PROFILE: "GAMING_PROFILE",
  LEADERBOARD: "GAMING_LEADERBOARD",
  STATS: "GAMING_STATS",
} as const;

export {
  AUTH_KEYS,
  GAMING_KEYS,
};

