const AUTH_KEYS = {
  CURRENT_USER: "CURRENT_USER",
} as const;

const TRACKER_KEYS = {
  CATEGORIES: "TRACKER_CATEGORIES",
  ACTIVE_TIMER: "TRACKER_ACTIVE_TIMER",
  SUMMARY: "TRACKER_SUMMARY",
} as const;

export { AUTH_KEYS, TRACKER_KEYS };
