export const USER_TYPES = {
  STUDENT: "STUDENT",
  TEACHER: "TEACHER",
  ADMIN: "ADMIN",
  MODERATOR: "MODERATOR",
};

export const TEACHER_RANKS = {
  PROFESSOR: "PROFESSOR",
  ASSOCIATE_PROFESSOR: "ASSOCIATE_PROFESSOR",
  ASSISTANT_PROFESSOR: "ASSISTANT_PROFESSOR",
  LECTURER: "LECTURER",
  INSTRUCTOR: "INSTRUCTOR",
};

export const GENDERS = {
  MALE: "MALE",
  FEMALE: "FEMALE",
};

export const EDUCATION_LEVELS = {
  UNIVERSITY: "UNIVERSITY",
  K12: "K12",
};

export const RELIGIONS = {
  ISLAM: "ISLAM",
  HINDU: "HINDU",
  CHRISTIAN: "CHRISTIAN",
  OTHERS: "OTHERS",
};

