export const FEATURE_FLAGS = {
  HOME: true,
  PROFILE: false,
  SEARCH: true,
  CR_CORNER: true,
  GROUPS: true,
  CLASSROOM: true,
  INSTITUTIONS: true,
  DEPARTMENTS: true,
  FRIENDS: true,
  GAMING: true,
  NOTIFICATIONS: true,
  MESSAGES: true,
  STUDY_HELPER: true,
  OPEN_DISCUSSION: true,
  CAREER_HUB: true,
  STORE: true,
  TUITION: true,
  VIDEOS: true,
  MORE: true,
  SETTINGS: true,
  FILES: true,
  SAVED: true,
  BLOOD_DONATION: true,
  BOX: true,
  QUICK_SHARE: true,
};
